### ISSUE TITLE
opt_constant_string_type can crash

### ISSUE THREAD

**Issue by jrmbchtl** [thewhiteninja/deobshell#3]
cst_string_node.text can be None, so trying to do
member = cst_string_node.text.lower() will crash in this case

Fix:
just insert
`if cst_string_node.text is None:
    continue`
inbetween
`for cst_string_node in node.findall("StringConstantExpressionAst"):`
and
`member = cst_string_node.text.lower()`

**Comment by thewhiteninja** [comment]
fixed in cc322c2982bf14fa937049ed64b102bdbf625416
Thanks for the bug report!
